"""Output guardrail pipeline.

Runs all output guards in order after retrieval and before the response
reaches the user:
  1. ProductGrounding — most critical: ensures no hallucinated products
  2. OutputSafety    — blocks internal information leakage
  3. ToneGuard       — ensures professional, parent-appropriate language

Schema validation is called separately when a structured dict is available.
"""
from __future__ import annotations

import time
from typing import Any, List, Tuple

from app.guardrails.models.guardrail_result import GuardrailResult
from app.guardrails.models.guarded_response import GuardedResponse
from app.guardrails.output.product_grounding_guard import check_product_grounding
from app.guardrails.output.safety_guard import check_safety_output
from app.guardrails.output.tone_guard import check_tone
from app.guardrails.pipeline._utils import _elapsed_ms
from app.config import get_logger

logger = get_logger(__name__)

_NO_MATCH_FALLBACK = "No matching products found. Please try a different search — maybe adjust the colour, age group, or price range."
_GENERIC_FALLBACK = "Here are the products I found for you. Please check the details below."


def run_output_guardrails(
    message: str,
    products: List[Any],
    retrieved_ids: List[int],
    query: str = "",
) -> Tuple[GuardedResponse, float]:
    """Run all output guardrails and return (GuardedResponse, latency_ms).

    Args:
        message: the text response generated by the system.
        products: structured product list attached to the response.
        retrieved_ids: authoritative IDs from the retrieval layer.

    Returns:
        GuardedResponse with final_response set to message or a safe fallback.
    """
    t0 = time.perf_counter()
    results: list[GuardrailResult] = []
    final_message = message

    # ── 1. Product Grounding ─────────────────────────────────────────────────
    r = check_product_grounding(products, retrieved_ids, query=query)
    results.append(r)
    if not r.passed:
        logger.warning("output_guardrail_failed", guardrail=r.guardrail_name, reason=r.reason)
        elapsed = _elapsed_ms(t0)
        fallback = _NO_MATCH_FALLBACK if not products else _GENERIC_FALLBACK
        return GuardedResponse(
            original_response=message,
            final_response=fallback,
            guardrail_results=results,
            fallback_used=True,
        ), elapsed

    # ── 2. Output Safety ─────────────────────────────────────────────────────
    r = check_safety_output(final_message)
    results.append(r)
    if not r.passed:
        logger.warning("output_guardrail_failed", guardrail=r.guardrail_name, reason=r.reason)
        elapsed = _elapsed_ms(t0)
        return GuardedResponse(
            original_response=message,
            final_response=_GENERIC_FALLBACK,
            guardrail_results=results,
            fallback_used=True,
        ), elapsed

    # ── 3. Tone ──────────────────────────────────────────────────────────────
    r = check_tone(final_message)
    results.append(r)
    if not r.passed:
        logger.warning("output_guardrail_failed", guardrail=r.guardrail_name, reason=r.reason)
        elapsed = _elapsed_ms(t0)
        return GuardedResponse(
            original_response=message,
            final_response=_GENERIC_FALLBACK,
            guardrail_results=results,
            fallback_used=True,
        ), elapsed

    elapsed = _elapsed_ms(t0)
    logger.info("output_guardrails_passed", latency_ms=elapsed)
    return GuardedResponse(
        original_response=message,
        final_response=final_message,
        guardrail_results=results,
        fallback_used=False,
    ), elapsed


